In [1]:
import numpy as np

import nnfs
from nnfs.datasets import spiral_data

from network.layers import Dense
from network.activations import ReLU, Softmax
from network.losses import CategoricalCrossentropy

In [2]:
nnfs.init()

In [3]:
# Data
X, y = spiral_data(100, 3)

In [4]:
dense1 = Dense(2, 3)
activation1 = ReLU()
dense2 = Dense(3, 3)
activation2 = Softmax()


In [5]:
dense1.forward(X)
activation1.forward(dense1.output)
dense2.forward(activation1.output)
activation2.forward(dense2.output)
loss_function = CategoricalCrossentropy()

In [6]:
loss = loss_function.calculate(activation2.output, y)

predictions = np.argmax(activation2.output, axis=1)
if len(y.shape) == 2:
    y = np.argmax(y, axis=1)
accuracy = np.mean(predictions == y)


In [7]:
print(activation2.output[:5])

print(f"acc: {accuracy}")
print(f"loss: {loss}")

[[0.33333334 0.33333334 0.33333334]
 [0.3333332  0.3333332  0.33333364]
 [0.3333329  0.33333293 0.3333342 ]
 [0.3333326  0.33333263 0.33333477]
 [0.33333233 0.3333324  0.33333528]]
acc: 0.34
loss: 1.0986104011535645
