In [1]:
import numpy as np

import nnfs
from nnfs.datasets import spiral_data

from network.layers import Dense
from network.activations import ReLU, Softmax
from network.losses import CategoricalCrossentropy
from network.commons import ActivationSoftmaxLossCategoricalCrossentropy

In [2]:
nnfs.init()

In [3]:
# Data
X, y = spiral_data(100, 3)

In [4]:
dense1 = Dense(2, 3)
activation1 = ReLU()
dense2 = Dense(3, 3)
activation_loss = ActivationSoftmaxLossCategoricalCrossentropy()

In [5]:
# Forward pass
dense1.forward(X)
activation1.forward(dense1.output)
dense2.forward(activation1.output)
loss = activation_loss.forward(dense2.output, y)

In [6]:
predictions = np.argmax(activation_loss.output, axis=1)
if y.ndim == 2:
    y = np.argmax(y, axis=1)
accuracy = np.mean(predictions == y)

print(activation_loss.output[:5])

print(f"acc: {accuracy}")
print(f"loss: {loss}")

[[0.33333334 0.33333334 0.33333334]
 [0.3333332  0.3333332  0.33333364]
 [0.3333329  0.33333293 0.3333342 ]
 [0.3333326  0.33333263 0.33333477]
 [0.33333233 0.3333324  0.33333528]]
acc: 0.34
loss: 1.0986104011535645


In [7]:
# Backpass
activation_loss.backward(activation_loss.output, y)
dense2.backward(activation_loss.dinputs)
activation1.backward(dense2.dinputs)
dense1.backward(activation1.dinputs)

In [8]:
# Print gradients
print(dense1.dweights)
print(dense1.dbiases)
print(dense2.dweights)
print(dense2.dbiases)

[[ 1.5766357e-04  7.8368583e-05  4.7324400e-05]
 [ 1.8161038e-04  1.1045573e-05 -3.3096312e-05]]
[[-3.60553473e-04  9.66117223e-05 -1.03671395e-04]]
[[ 5.44109462e-05  1.07411419e-04 -1.61822361e-04]
 [-4.07913431e-05 -7.16780924e-05  1.12469446e-04]
 [-5.30112993e-05  8.58172934e-05 -3.28059905e-05]]
[[-1.0729185e-05 -9.4610732e-06  2.0027859e-05]]
